<?php

/**
 * Created by PhpStorm.
 * User: hdqjoy
 * Date: 2018/4/1
 * Time: 9:55
 */
namespace app\common\controller;

use think\Controller;

class Base extends Controller
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        
    }


}