<?php
/**
 * Created by PhpStorm.
 * User: hdqjoy
 * Date: 2018/5/31
 */

namespace app\demo\controller;

use app\common\controller\Base;
use think\facade\Session;
use think\Request;


class DemoBase extends Base
{

    public $id;
    public $admin_name;
    public $account;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 如果没有登录，跳转到登录；如果登录了，跳转到首页
        if (!Session::has('id') || Session::get('id') == '' || Session::get('id') == null) {

            $this->redirect(url('Admin/Login/index'));
        }
    }
}