<?php
/**
 * Created by PhpStorm.
 * User: hdqjoy
 * Date: 2018/3/31
 * Time: 15:34
 */

namespace app\admin\controller;

use app\common\controller\Base;
use think\facade\Session;


class AdminBase extends Base
{

    public $id;
    public $admin_name;
    public $account;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 如果没有登录，跳转到登录；如果登录了，跳转到首页
        if(!Session::has('id') || Session::get('id') == '' || Session::get('id') == null ){

            $this->redirect(url('Login/index'));
        }else{

        }
    }
    

}